import { useCallback,useEffect,useMemo,useState } from 'react';
import { sketches } from './data';
import { createTranslator,detectLocale,localize } from './i18n';
import type { Outcome,Phase } from './types';
import './LastLaughClub.less';
const SOUND_KEY='last_laugh_club_sound_v1';
function rotate(outcomes:[Outcome,Outcome,Outcome],offset:number){return outcomes.map((_,i)=>outcomes[(i+offset)%outcomes.length]);}
function initialOffsets(){return sketches.map(()=>Math.floor(Math.random()*3));}
function SpeakerIcon({muted}:{muted:boolean}){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M4 9h4l5-4v14l-5-4H4z"/>{muted?<path d="m16 9 5 6m0-6-5 6"/>:<path d="M16 8c1.7 2.2 1.7 5.8 0 8M19 5c3.4 4 3.4 10 0 14"/>}</svg>}
function ArrowIcon(){return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h13M13 6l6 6-6 6"/></svg>}
export function LastLaughClub(){
 const locale=useMemo(detectLocale,[]),t=useMemo(()=>createTranslator(locale),[locale]);
 const [phase,setPhase]=useState<Phase>('cover'),[sketchIndex,setSketchIndex]=useState(0),[selected,setSelected]=useState<Outcome|null>(null),[offsets,setOffsets]=useState(initialOffsets),[mediaReady,setMediaReady]=useState(false),[soundEnabled,setSoundEnabled]=useState(()=>localStorage.getItem(SOUND_KEY)!=='off');
 const sketch=sketches[sketchIndex],media=`./media/${sketch.mediaDir}/`,ordered=useMemo(()=>rotate(sketch.outcomes,offsets[sketchIndex]),[offsets,sketch,sketchIndex]),duration=phase==='performance'&&selected?selected.videoTime:sketch.setupVideoTime;
 const toggleSound=useCallback(()=>setSoundEnabled(v=>{const n=!v;localStorage.setItem(SOUND_KEY,n?'on':'off');return n}),[]);
 const start=useCallback(()=>{setSketchIndex(0);setOffsets(initialOffsets());setSelected(null);setMediaReady(false);setPhase('setup')},[]);
 const pick=useCallback((o:Outcome)=>{if(phase!=='question')return;setSelected(o);setMediaReady(false);setPhase('performance')},[phase]);
 const finishSetup=useCallback(()=>setPhase(v=>v==='setup'?'question':v),[]),finishResult=useCallback(()=>setPhase(v=>v==='performance'?'verdict':v),[]);
 const advance=useCallback(()=>{if(!selected?.success){setOffsets(v=>v.map((n,i)=>i===sketchIndex?n+1:n));setSelected(null);setPhase('question');return}if(sketchIndex<sketches.length-1){setSketchIndex(v=>v+1);setSelected(null);setMediaReady(false);setPhase('setup');return}setSketchIndex(0);setSelected(null);setPhase('cover')},[selected,sketchIndex]);
 useEffect(()=>{if(phase!=='setup'&&phase!=='performance')return;const id=window.setTimeout(phase==='setup'?finishSetup:finishResult,duration*1000+600);return()=>window.clearTimeout(id)},[duration,finishResult,finishSetup,phase]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if(e.key.toLowerCase()==='m')toggleSound();else if(phase==='cover'&&e.key==='Enter')start();else if(phase==='question'&&['1','2','3'].includes(e.key))pick(ordered[Number(e.key)-1]);else if(phase==='verdict'&&e.key==='Enter')advance()};window.addEventListener('keydown',onKey);return()=>window.removeEventListener('keydown',onKey)},[advance,ordered,phase,pick,start,toggleSound]);
 return <main className="llc-shell"><article className={`llc-stage llc-stage--${phase}`}>
  <header className="llc-topbar"><div className="llc-progress-dots">{sketches.map((item,i)=><i key={item.id} className={i<=sketchIndex?'is-active':''}/>)}</div><span>{localize(sketch.label,locale)}</span><button type="button" onPointerDown={toggleSound} aria-label={soundEnabled?t('soundOn'):t('soundOff')}><SpeakerIcon muted={!soundEnabled}/></button></header>
  {phase==='cover'&&<section className="llc-cover"><img src="./media/sketch1/setup_start.webp" alt={locale==='zh'?'Elena 在订婚宴服务香槟':'Elena serving champagne at an engagement dinner'} draggable={false}/><div className="llc-cover__shade"/><div className="llc-cover__copy"><span>{t('anthology')}</span><h1><b>{t('titleTop')}</b><b>{t('titleBottom')}</b></h1><p>{t('deck')}</p></div><button className="llc-primary" type="button" onPointerDown={start}><span>{t('start')}</span><ArrowIcon/></button></section>}
  {phase==='setup'&&<section className="llc-video"><img src={`${media}setup_start.webp`} alt="" draggable={false}/><video key={`${sketch.id}-setup`} src={`${media}setup.mp4`} autoPlay muted={!soundEnabled} playsInline preload="auto" poster={`${media}setup_start.webp`} onCanPlay={()=>setMediaReady(true)} onEnded={finishSetup}/><div className="llc-caption">{localize(sketch.setupCaption,locale)}</div>{!mediaReady&&<div className="llc-loading">{t('loading')}</div>}<div className="llc-time" style={{'--llc-duration':`${sketch.setupVideoTime}s`} as React.CSSProperties}><i/></div></section>}
  {phase==='question'&&<section className="llc-question"><div className="llc-question__image"><img src={`${media}choice.webp`} alt={localize(sketch.choiceAlt,locale)} draggable={false}/><div><span>{localize(sketch.conflict,locale)}</span><strong>{localize(sketch.question,locale)}</strong></div></div><div className="llc-choices"><h2>{t('choose')}</h2>{ordered.map((o,i)=><button key={o.id} type="button" onPointerDown={()=>pick(o)}><span>{i+1}</span><strong>{localize(o.label,locale)}</strong></button>)}</div></section>}
  {phase==='performance'&&selected&&<section className="llc-video"><img src={`${media}choice.webp`} alt="" draggable={false}/><video key={`${sketch.id}-${selected.id}`} src={`${media}${selected.id}.mp4`} autoPlay muted={!soundEnabled} playsInline preload="auto" poster={`${media}choice.webp`} onCanPlay={()=>setMediaReady(true)} onEnded={finishResult}/><div className="llc-caption">{localize(selected.label,locale)}</div>{!mediaReady&&<div className="llc-loading">{t('loading')}</div>}<div className="llc-time" style={{'--llc-duration':`${selected.videoTime}s`} as React.CSSProperties}><i/></div></section>}
  {phase==='verdict'&&selected&&<section className={`llc-verdict llc-verdict--${selected.success?'success':'failure'}`}><img src={`${media}${selected.id}_end.webp`} alt="" draggable={false}/><div className="llc-verdict__line"/><div className="llc-verdict__copy"><span>{selected.success?t('passed'):t('failed')}</span><h2>{localize(selected.resultTitle,locale)}</h2><p>{localize(selected.resultDetail,locale)}</p><button className="llc-primary" type="button" onPointerDown={advance}><b>{selected.success?localize(sketch.nextLabel,locale):t('retry')}</b><ArrowIcon/></button></div></section>}
  <footer><span>LAST LAUGH CLUB</span><img src="./alteru.svg" alt={t('watermark')} draggable={false}/><span>{localize(sketch.reclaimed,locale)}</span></footer>
 </article></main>
}
